language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO_VERSION="Django<2"
  - DJANGO_VERSION="Django<2.1"
  - DJANGO_VERSION="Django<2.2"
  - DJANGO_VERSION="Django<2.3"


matrix:
  exclude:
    - python: "3.7"
      env: DJANGO_VERSION="Django<2"
    - python: "2.7"
      env: DJANGO_VERSION="Django<2.1"
    - python: "2.7"
      env: DJANGO_VERSION="Django<2.2"
    - python: "2.7"
      env: DJANGO_VERSION="Django<2.3"
    - python: "3.4"
      env: DJANGO_VERSION="Django<2.2"

# command to install dependencies
install:
  - pip install $DJANGO_VERSION
  - pip install -r requirements-dev.txt

# command to run tests

script:
  - python run_tests.py
