language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO_VERSION=Django==1.5
  - DJANGO_VERSION=Django==1.6
  - DJANGO_VERSION=Django==1.7
  - DJANGO_VERSION=Django==1.8

# command to install dependencies
install:
  - pip install $DJANGO_VERSION
  - pip install -r requirements-dev.txt

# command to run tests

script:
  - python run_tests.py
